In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6,7]

In [3]:
a

[1, 2, 3, 4, 5, 6, 7]

In [4]:
print(type(a))

<class 'list'>


In [5]:
np_a =np.array(a)

In [6]:
print(np_a)

[1 2 3 4 5 6 7]


In [7]:
print(type(np_a))

<class 'numpy.ndarray'>


In [8]:
L = range(10000)
%timeit [i**2 for i in L]

662 µs ± 25.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
a = np .arange(100000)
%timeit a**2

64.2 µs ± 9.71 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
a.ndim

1

In [12]:
a.shape

(4,)

In [13]:
b= np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 4)

In [16]:
c=np.array([[[0,1,2],[4,5,6],[7,8,9]]])
c

array([[[0, 1, 2],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
c.ndim

3

In [18]:
b.shape

(2, 4)

In [19]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [20]:
np.array(my_list)

array([1, 2, 3])

In [21]:
matrix =[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.array(matrix).shape

(3, 3)

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b=np.arange(1,50,6)

In [26]:
b

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

In [27]:
a= np.linspace(0,6,7)

In [28]:
a

array([0., 1., 2., 3., 4., 5., 6.])

In [29]:
np.linspace(0,69,7)

array([ 0. , 11.5, 23. , 34.5, 46. , 57.5, 69. ])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
b =np.zeros((3,3))

In [32]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
a = np.ones((7,8))

In [34]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
c = np.eye(3)

In [36]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [38]:
a =np.diag([7,8,9,10])
a

array([[ 7,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [39]:
np.diag(a)

array([ 7,  8,  9, 10])

In [40]:
random_array = np.random.randint(1,121,5)
print(random_array)

[57 74 32 98 51]


In [41]:
a = np.random.rand(4)
a

array([0.14558155, 0.71535866, 0.86562098, 0.04611112])

In [42]:
a=np.random.randn(100)
a

array([ 0.42658434, -0.94801441, -1.77975857, -0.2409426 , -1.3718658 ,
       -1.2720464 ,  0.34488997, -0.13854647, -1.94205638,  0.53708783,
        1.38981278, -1.01338337,  0.49159021, -0.64569598, -1.35291007,
       -1.01303405, -0.15157142,  0.41806071, -0.5195786 ,  1.36621003,
       -1.87281943, -0.00896297, -0.08579322, -0.45418373,  0.73858222,
       -1.28246486, -0.62450574,  1.93176992, -0.0029173 ,  0.40183286,
       -0.87754684,  0.54343772, -1.42342529, -1.18154085,  0.53926358,
        0.21296333, -1.81466115,  0.77467442, -0.6720249 , -0.94764358,
       -0.44794082, -0.24450559,  2.04867436, -1.23209751, -0.2420364 ,
       -0.07548508,  0.93542527, -0.61255386,  0.29608093,  0.2235012 ,
        0.56829002,  2.07683415, -0.16502621, -1.38968535, -0.04463064,
       -0.35630723, -0.84419916,  0.35539759, -0.45175265,  0.35207865,
       -0.33919391, -1.35165075, -0.00466806,  0.2833891 ,  0.30554705,
        1.05232245, -0.67405056, -0.34500589, -1.08325958,  1.48

In [43]:
a = np.array([1,2,3])
b = a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [44]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [45]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a: {}".format(b.shape))

[[1 2 3]
 [4 5 6]]
shape of a: (3,)


In [47]:
b=a.reshape(3,2)
print(b)
print("shape of b:{}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
shape of b:(3, 2)


In [48]:
a=np.array([[1,2,3],[4,5,6]])
print("shape:{}".format(a.shape))
print(a)

shape:(2, 3)
[[1 2 3]
 [4 5 6]]


In [49]:
c=a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [50]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [51]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [52]:
a = np.array([[5,4,6],[2,8,7]])
b=np.sort(a,axis=1)

In [53]:
b

array([[4, 5, 6],
       [2, 7, 8]])

In [54]:
a= np.array([4,9,8])
a= np.append(a,[2,6,7])
print('np array after addition:',a)

np array after addition: [4 9 8 2 6 7]


In [55]:
a= np.delete(a,2)
print('np array after deletion of one element:',a)

np array after deletion of one element: [4 9 2 6 7]


In [57]:
a= np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [63]:
a= np.diag(([1,2,3]))
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [65]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [67]:
a= np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [69]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [3]:
a= np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [5]:
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [7]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [9]:
b[::-1]

array([4, 3, 2, 1, 0])

In [11]:
a[5:]=b[::-1]

In [13]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [15]:
a = np.random.randint(0,20,5)
a

array([16,  3, 18, 13,  7])

In [17]:
a[a % 2 ==0]

array([16, 18])

In [19]:
a[a % 2 ==0] = -1
a

array([-1,  3, -1, 13,  7])

In [21]:
a = np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [25]:
a[[9,7]]= -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

In [27]:
a = np.array([1,2,3,4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [29]:
a ** 2

array([ 1,  4,  9, 16])

In [31]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [33]:
a - b

array([-1.,  0.,  1.,  2.])

In [35]:
a*b

array([2., 4., 6., 8.])

In [37]:
a=np.array([[1,2],[3,4],[4,6]])
b=np.array([[4,4],[4,4],[4,4]])

print(a*b)

[[ 4  8]
 [12 16]
 [16 24]]


In [39]:
print(a*b)

[[ 4  8]
 [12 16]
 [16 24]]


In [41]:
c=np.diag([1,2,3,4])
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [49]:
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[1,2,1],[3,4,3],[5,6,5]])
print("matrix multiplication:\n" np.matmul(a,b))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2038407215.py, line 3)

In [51]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [53]:
a > b

array([False, False,  True, False])

In [55]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.array([1,2,3,4])


In [57]:
np.array_equal(a,b)

True

In [59]:
np.array_equal(a,c)

True

In [61]:
a = np.array([1,1,0,0],dtype = bool)
b = np.array([1,1,0,0],dtype = bool)
np.logical_or(a,b)

array([ True,  True, False, False])

In [63]:
np.logical_and(a,b)

array([ True,  True, False, False])

In [65]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [67]:
np.log(a)

C:\Users\Dell\AppData\Local\Temp\ipykernel_8900\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [69]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [71]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [73]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [75]:
x= np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [77]:
x.sum(axis=0)

array([3, 3])

In [79]:
x.sum(axis=1)

array([2, 4])

In [81]:
x = np.array([1,3,2])
x.min()

1

In [83]:
x.max()

3

In [85]:
x.argmin()

0

In [87]:
x.argmax()

1

In [89]:
normal_array = np.arange(0,10,1)
print('Array is', format(normal_array))


print('min element is', np.min(normal_array))



print('max element is', np.max(normal_array))



print('Sum of elements in array is', np.sum(normal_array))



print('mean of elements in array is', np.mean(normal_array))


print('median of elements in array is',np.median(normal_array))



print('standard deviation of elements in array is ',np.std(normal_array))

Array is [0 1 2 3 4 5 6 7 8 9]
min element is 0
max element is 9
Sum of elements in array is 45
mean of elements in array is 4.5
median of elements in array is 4.5
standard deviation of elements in array is  2.8722813232690143
